#!/bin/bash

result=$(sed -n "s/seq \([0-9]*\) \([0-9]*\) | parallel -j 5 -u/\1 \2/p" /nobackup/csjone15/pleiades_llc_recipes/python_cli_data_export/surf_extract/parallel_extract.sh)
integer1=$(echo "$result" | awk '{print $1}')
integer2=$(echo "$result" | awk '{print $2}')

echo $integer1
echo $integer2
