name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab=1.0.1
  - tornado=6.0.3
  - bokeh
  - dask>=2.0.0
  - jupyter-server-proxy
  - ipywidgets
  - graphviz
  - dask-labextension==0.3.3
  - dask-jobqueue
  - dask-mpi
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray>=0.12.2
  - dask>=2.0.0
  - scikit-image
  - scikit-learn
  - holoviews
  - panel
  - geoviews
  - hvplot
  - geoviews
  - datashader
  - cartopy
  - netcdf4
  - h5py
  - h5netcdf
  - regionmask
  - gsw
  - intake
  - intake-xarray
  - intake-esm
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - fsspec
  - xgcm
  - xrft
  - xmitgcm>=0.4.1
  - xhistogram
  - pip
