#!/bin/bash
 
directory_path="/nobackup/csjone15/pleiades_llc_recipes/python_cli_data_export/surf_extract/surf_wind"

# Check if there are any files in the directory
#if [ -n "$(ls -A "$directory_path")" ]; then
#    echo "Files found in the directory. Exiting..."
#    exit 1
#fi


counter=0

csv_file="/nobackup/csjone15/pleiades_llc_recipes/checking_infra/checklist_wind.csv"

# Read the CSV file line by line
while IFS= read -r line; do
    # Extract the values from the line
    values=$(echo "$line" | cut -d',' -f2-)
    # Check if the values are "0,0,0,0"
    if [ "$values" == "0,0,0,0,0" ]; then
	if ((counter==0))
	then
        iterno=$(echo "$line" | sed -n 's/llc4320\_KPPhbl\-PhiBot\-oceTAUX\-oceTAUY\-SIarea\_f.\_k0\_iter\_\([0-9]*\),0,0,0,0,0/\1/p')
        ts=$((($iterno-179856) / 144))
        fi
	counter=$((counter+1))
	echo $counter
	if ((counter > 360))
	   then
	   break
        fi
    elif ((counter >0))
    then 
	    break
    fi
done < "$csv_file"
echo "Found iterno $ts for the first line with 0,0,0,0,0: $line"
echo $counter

result=$(sed -n "s/seq \([0-9]*\) \([0-9]*\) | parallel -j . -u/\1 \2/p" /nobackup/csjone15/pleiades_llc_recipes/python_cli_data_export/surf_extract/wind.pbs)
integer1=$(echo "$result" | awk '{print $1}')
integer2=$(echo "$result" | awk '{print $2}')

#if [[ "$integer1" -eq "$ts" ]]; then
#	exit 0 
#fi

starti=$ts
endi=$((ts+$counter/12-1))


sed -i "s/seq .* | parallel -j 4 -u \\\/seq $starti $endi | parallel -j 4 -u \\\/" /nobackup/csjone15/pleiades_llc_recipes/python_cli_data_export/surf_extract/wind.pbs

cd python_cli_data_export/surf_extract

one=$(qsub wind.pbs)
echo $one 

cd /nobackup/csjone15/pleiades_llc_recipes
two=$(qsub -W depend=afterok:$one checking_infra/kerch_wind.sh)
echo $two
three=$(qsub -W depend=afterok:$two checking_infra/transfer_wind.pbs)
echo $three
four=$(qsub -W depend=afterany:$three checking_infra/transfer_wind2.pbs)
echo $four
five=$(qsub -W depend=afterok:$four checking_infra/garbage_wind.sh)
echo $five
